// j-cli/templates/webpack-react/src/components/App/index.jsx
import React, { Component } from 'react';
import Logo from '../../assets/images/logo.png';
import axios from '../../utils/baseHttp';
import './index.css';

class App extends Component {
    render() {
        return (
            <div>
                <p>Good Luck</p>
                <img src={Logo} />
            </div>
        );
    };
};

export default App;

// j-cli/templates/webpack-vue2/src/App.vue
<template>
    <div>
        <p>Good Luck</p>
        <img :src="Logo">
    </div>
</template>

<script>
import Logo from '@assets/images/logo.png';

export default {
    data() {
        return {
            Logo,
        };
    },
};
</script>

<style scoped>
div{
    color: blue;
    margin: 0 auto;
    text-align: center;
    padding-top: 100px;
}
p{
    margin-bottom: 20px;
}
</style>
